### ISSUE TITLE
Fix publishing to PyPI

### ISSUE THREAD

**Issue by CasparJungbacker** [TeachBooks/TeachBooks#15]
I released a new version of the package, but [the publishing pipeline broke](https://github.com/TeachBooks/TeachBooks/actions/runs/10779431225) :( I think something went wrong in the stage where the package is uploaded to PyPI.

@rlanzafame do you have a smart computer science TA to take a look at this? @Tom-van-Woudenberg has the passwords to the PyPI account I believe.

**Comment by jeijkenboom** [comment]
It seems PyPi doesnt allow the same name to be used more than once for security reasons (https://pypi.org/help/#file-name-reuse). The name is automatically generated during the build stage from the `pyproject.toml` file. So just set the version in that file from `0.0.2 ` to `0.0.3`.

**Comment by Tom-van-Woudenberg** [comment]
@CasparJungbacker , is that enough for you?

**Comment by rlanzafame** [comment]
that was easy :)
see [this commit](https://github.com/TeachBooks/TeachBooks/commit/12fbe9dae92ed5f53c96e9d380292232bf9ab1a6)
