### ISSUE TITLE
add `teachbooks clean`

### ISSUE THREAD

**Issue by rlanzafame** [TeachBooks/TeachBooks#19]
when cleaning book with `jupyter book clean book` and using `teachbooks serve` the book cannot be cleaned ("used by another process" error). 

`teachbooks clean book` works as you would expect, like runnging `jupyter book clean book` but takes into account `teachbooks serve`, except it first identifies whether a local server is running and runs `teachbooks serve stop` before `jupyter book clean book`

**Comment by Tom-van-Woudenberg** [comment]
@rlanzafame  you can test this because I never use this functionality.
