### ISSUE TITLE
Setup documentation

### ISSUE THREAD

**Issue by CasparJungbacker** [TeachBooks/TeachBooks#2]
Demonstrate installation, explain what `teachbooks` is, explain the commands. Can also be another Jupyter Book, fits the theme nicely :)

**Comment by Tom-van-Woudenberg** [comment]
Robert: update remove from publish instructions, the line for the config is already there. need to add the bit about toc

**Comment by Tom-van-Woudenberg** [comment]
https://gitlab.tudelft.nl/interactivetextbooks-citg/jupyter-book-manual/-/issues/78

**Comment by Tom-van-Woudenberg** [comment]
@xjulie0x , can you add this to the manual?
As described here: https://teachbooks.github.io/TeachBooks/cli/cli.html on how to build
and described here: https://teachbooks.github.io/TeachBooks/cli/cli.html#teachbooks-build on how to start a local python server to test interactive featuers
